# Discovery Server Access
spring:
  application:
    name: services-info

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port