# Discovery Server Access
spring:
  application:
    name: inter-comm

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
    instance:
      hostname: localhost

# HTTP Server
server:
  port: 4450   # HTTP (Tomcat) port